<a href="https://colab.research.google.com/github/kendala545-dot/mis433/blob/main/Aaron_Kendall_IMDB_manipulation_summarization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment - Analyzing the IMDB Top 1000 Movies

In the next few assignments, you will be working with this data set of IMDB top 1000 movies.

Source: https://www.kaggle.com/harshitshankhdhar/imdb-dataset-of-top-1000-movies-and-tv-shows

In [ ]:
import pandas as pd
import numpy as np

To read the data file from your Google Drive, mount your drive first.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
# Read the data file "imdb_top_1000.csv" to a dataframe named "imdb"
imdb = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/imdb_top_1000.csv', header=0)
imdb.head()

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469"
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411"
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444"
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"57,300,000"
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"4,360,000"

In [ ]:
# Describe the dataframe using the info() method.
imdb.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Poster_Link    1000 non-null   object
 1   Series_Title   1000 non-null   object
 2   Released_Year  1000 non-null   object
 3   Certificate    899 non-null    object
 4   Runtime        1000 non-null   object
 5   Genre          1000 non-null   object
 6   IMDB_Rating    1000 non-null   float64
 7   Overview       1000 non-null   object
 8   Meta_score     843 non-null    float64
 9   Director       1000 non-null   object
 10  Star1          1000 non-null   object
 11  Star2          1000 non-null   object
 12  Star3          1000 non-null   object
 13  Star4          1000 non-null   object
 14  No_of_Votes    1000 non-null   int64
 15  Gross          831 non-null    object
dtypes: float64(2), int64(1), object(13)
memory usage: 125.1+ KB

In [ ]:
# List all the column names:
imdb.columns

Index(['Poster_Link', 'Series_Title', 'Released_Year', 'Certificate',
       'Runtime', 'Genre', 'IMDB_Rating', 'Overview', 'Meta_score', 'Director',
       'Star1', 'Star2', 'Star3', 'Star4', 'No_of_Votes', 'Gross'],
      dtype='object')

## Part 1: Data Manipulation

In [14]:
# Display top 10 movies' title, released year and IMDB rating.
imdb[['Series_Title', 'Released_Year', 'IMDB_Rating']].head(10)

                                    Series_Title Released_Year  IMDB_Rating
0                       The Shawshank Redemption          1994          9.3
1                                  The Godfather          1972          9.2
2                                The Dark Knight          2008          9.0
3                         The Godfather: Part II          1974          9.0
4                                   12 Angry Men          1957          9.0
5  The Lord of the Rings: The Return of the King          2003          8.9
6                                   Pulp Fiction          1994          8.9
7                               Schindler's List          1993          8.9
8                                      Inception          2010          8.8
9                                     Fight Club          1999          8.8

In [19]:
# Display movies ranked 11-20.
# Show their title, released year and IMDB rating.
imdb[['Series_Title', 'Released_Year', 'IMDB_Rating']].iloc[10:21]

,Series_Title,Released_Year,IMDB_Rating
10,The Lord of the Rings: The Fellowship of the Ring,2001,8.8
11,Forrest Gump,1994,8.8
12,"Il buono, il brutto, il cattivo",1966,8.8
13,The Lord of the Rings: The Two Towers,2002,8.7
14,The Matrix,1999,8.7
15,Goodfellas,1990,8.7
16,Star Wars: Episode V - The Empire Strikes Back,1980,8.7
17,One Flew Over the Cuckoo's Nest,1975,8.7
18,Hamilton,2020,8.6
19,Gisaengchung,2019,8.6
20,Soorarai Pottru,2020,8.6

In [28]:
# Select all movies directed by Quentin Tarantino.
# Show their title, released year, IMDB rating, and gross.
tarantino_movies = imdb[imdb["Director"] == 'Quentin Tarantino']
tarantino_movies[['Series_Title', 'Released_Year', 'IMDB_Rating', 'Gross']]

                         Series_Title Released_Year  IMDB_Rating        Gross
6                        Pulp Fiction          1994          8.9  107,928,762
62                   Django Unchained          2012          8.4  162,805,434
93               Inglourious Basterds          2009          8.3  120,540,719
103                    Reservoir Dogs          1992          8.3    2,832,029
241                 Kill Bill: Vol. 1          2003          8.1   70,099,045
369                 Kill Bill: Vol. 2          2004          8.0   66,208,183
584                 The Hateful Eight          2015          7.8   54,117,416
879  Once Upon a Time... in Hollywood          2019          7.6  142,502,728

In [38]:
# Select all R rated movies with IMDB_Rating>=8.5
# Show their title, released year, certificate, and IMDB rating.
movies = imdb[(imdb['Certificate'] == 'R') & (imdb['IMDB_Rating'] >= 8.5)]
movies[['Series_Title', 'Released_Year', 'IMDB_Rating']]

           Series_Title Released_Year  IMDB_Rating
24  Saving Private Ryan          1998          8.6
38          The Pianist          2002          8.5
40   American History X          1998          8.5

In [40]:
# How many unique values are there in the column "Released_Year"?
# Hint: nunique()
imdb['Released_Year'].nunique()

100

In [42]:
# Count the number of movies in each "Released_Year"?
# Hint: value_counts()
imdb['Released_Year'].value_counts()

Released_Year
2014    32
2004    31
2009    29
2013    28
2016    28
        ..
1920     1
1930     1
1922     1
1943     1
PG       1
Name: count, Length: 100, dtype: int64

In [47]:
# In this dataset, there is a movie with an error in "Released_Year".
# Hint: Released_Year should be a 4-digit integer but this movie's is not.
# Find this movie.
imdb[imdb['Released_Year'] == 'PG']

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
966,https://m.media-amazon.com/images/M/MV5BNjEzYj...,Apollo 13,PG,U,140 min,"Adventure, Drama, History",7.6,NASA must devise a strategy to return Apollo 1...,77.0,Ron Howard,Tom Hanks,Bill Paxton,Kevin Bacon,Gary Sinise,269197,"173,837,933"

In [48]:
# Correct the values for the corresponding columns ("Released_Year" and "Certificate").
# You may want to look up this movie on www.imdb.com.
# Hint: You can set value for a particular row by: df.loc[row_name, column_name] = new_value

# Find the index of the movie 'Apollo 13'
apollo13_index = imdb[imdb['Series_Title'] == 'Apollo 13'].index[0]

# Correct 'Released_Year' to '1995'
imdb.loc[apollo13_index, 'Released_Year'] = '1995'

# Correct 'Certificate' to 'PG'
imdb.loc[apollo13_index, 'Certificate'] = 'PG'

# Display the corrected row to verify
display(imdb.loc[apollo13_index, ['Series_Title', 'Released_Year', 'Certificate']])

Series_Title     Apollo 13
Released_Year         1995
Certificate             PG
Name: 966, dtype: object

In [49]:
# Change the data type of "Released_Year" to int
imdb['Released_Year'] = imdb['Released_Year'].astype(int)
display(imdb['Released_Year'].info())

<class 'pandas.core.series.Series'>
RangeIndex: 1000 entries, 0 to 999
Series name: Released_Year
Non-Null Count  Dtype
--------------  -----
1000 non-null   int64
dtypes: int64(1)
memory usage: 7.9 KB

None

In [56]:
# Select all movies released after (>=) 2010 and with IMDB_Rating>=8.5
# Show their title, released year, certificate, and IMDB rating.
movies = imdb[(imdb['Released_Year'] >= 2010) & (imdb['IMDB_Rating'] >= 8.5)]
movies[['Series_Title', 'Released_Year', 'Certificate', 'IMDB_Rating']]

        Series_Title  Released_Year Certificate  IMDB_Rating
8          Inception           2010          UA          8.8
18          Hamilton           2020       PG-13          8.6
19      Gisaengchung           2019           A          8.6
20   Soorarai Pottru           2020           U          8.6
21      Interstellar           2014          UA          8.6
33             Joker           2019           A          8.5
34          Whiplash           2014           A          8.5
35  The Intouchables           2011          UA          8.5

In [57]:
# Select all movies whose genres contain 'Animation'
animation_movies = imdb[imdb['Genre'].str.contains('Animation')]
animation_movies[['Series_Title', 'Genre', 'Released_Year', 'IMDB_Rating']]

,Series_Title,Genre,Released_Year,IMDB_Rating
23,Sen to Chihiro no kamikakushi,"Animation, Adventure, Family",2001,8.6
43,The Lion King,"Animation, Adventure, Drama",1994,8.5
46,Hotaru no haka,"Animation, Drama, War",1988,8.5
56,Kimi no na wa.,"Animation, Drama, Fantasy",2016,8.4
58,Spider-Man: Into the Spider-Verse,"Animation, Action, Adventure",2018,8.4
...,...,...,...,...
956,Mulan,"Animation, Adventure, Family",1998,7.6
971,Omohide poro poro,"Animation, Drama, Romance",1991,7.6
976,The Little Mermaid,"Animation, Family, Fantasy",1989,7.6
986,Watership Down,"Animation, Adventure, Drama",1978,7.6
992,The Jungle Book,"Animation, Adventure, Family",1967,7.6

In [58]:
# Create a new dataframe called "stars" including the following columns:
# Series_Title, Released_Year, Star1, Star2, Star3, Star4
stars = imdb[['Series_Title', 'Released_Year', 'Star1', 'Star2', 'Star3', 'Star4']]
stars

,Series_Title,Released_Year,Star1,Star2,Star3,Star4
0,The Shawshank Redemption,1994,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler
1,The Godfather,1972,Marlon Brando,Al Pacino,James Caan,Diane Keaton
2,The Dark Knight,2008,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine
3,The Godfather: Part II,1974,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton
4,12 Angry Men,1957,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler
...,...,...,...,...,...,...
995,Breakfast at Tiffany's,1961,Audrey Hepburn,George Peppard,Patricia Neal,Buddy Ebsen
996,Giant,1956,Elizabeth Taylor,Rock Hudson,James Dean,Carroll Baker
997,From Here to Eternity,1953,Burt Lancaster,Montgomery Clift,Deborah Kerr,Donna Reed
998,Lifeboat,1944,Tallulah Bankhead,John Hodiak,Walter Slezak,William Bendix
999,The 39 Steps,1935,Robert Donat,Madeleine Carroll,Lucie Mannheim,Godfrey Tearle

In [59]:
# Create a new dataframe called "genres" including the following columns:
# Series_Title, Released_Year, Genre.
genres = imdb[['Series_Title', 'Released_Year', 'Genre']]
genres

                 Series_Title  Released_Year                     Genre
0    The Shawshank Redemption           1994                     Drama
1               The Godfather           1972              Crime, Drama
2             The Dark Knight           2008      Action, Crime, Drama
3      The Godfather: Part II           1974              Crime, Drama
4                12 Angry Men           1957              Crime, Drama
..                        ...            ...                       ...
995    Breakfast at Tiffany's           1961    Comedy, Drama, Romance
996                     Giant           1956            Drama, Western
997     From Here to Eternity           1953       Drama, Romance, War
998                  Lifeboat           1944                Drama, War
999              The 39 Steps           1935  Crime, Mystery, Thriller

[1000 rows x 3 columns]

In [60]:
# Sorting:
# Sort dataframe genres in ascending order of "Released_Year"
genres_sorted = genres.sort_values(by='Released_Year', ascending=True)
genres_sorted

                     Series_Title  Released_Year                         Genre
321  Das Cabinet des Dr. Caligari           1920      Fantasy, Horror, Mystery
127                       The Kid           1921         Comedy, Drama, Family
568                     Nosferatu           1922               Fantasy, Horror
194                  Sherlock Jr.           1924       Action, Comedy, Romance
193                 The Gold Rush           1925      Adventure, Comedy, Drama
..                            ...            ...                           ...
612    The Trial of the Chicago 7           2020      Drama, History, Thriller
613                          Druk           2020                 Comedy, Drama
20                Soorarai Pottru           2020                         Drama
18                       Hamilton           2020     Biography, Drama, History
205                          Soul           2020  Animation, Adventure, Comedy

[1000 rows x 3 columns]

In [63]:
# Select all movies released after (>=) 2010 and with IMDB_Rating>=8.5
# Show their title, released year, Certificate, and gross.
# Sort them in descending order of "Gross"

movies = imdb[(imdb['Released_Year'] >= 2010) & (imdb['IMDB_Rating'] >= 8.5)]
movies[['Series_Title', 'Released_Year', 'Certificate', 'Gross']].sort_values(by='Gross', ascending=False)

        Series_Title  Released_Year Certificate        Gross
33             Joker           2019           A  335451311.0
8          Inception           2010          UA  292576195.0
21      Interstellar           2014          UA  188020017.0
19      Gisaengchung           2019           A   53367844.0
35  The Intouchables           2011          UA   13182281.0
34          Whiplash           2014           A   13092000.0
18          Hamilton           2020       PG-13          NaN
20   Soorarai Pottru           2020           U          NaN

In [ ]:
# Does the sorting result look right to you? What's the problem?
# They are in descending order by gross except the first row should be lower and was sorted wrong

In [62]:
# Resolve this problem of "Gross" and convert its data type to float
# Hint: You may find this webpage useful:
# https://stackoverflow.com/questions/28986489/how-to-replace-text-in-a-column-of-a-pandas-dataframe

# Remove commas from the 'Gross' column and convert to numeric, coercing errors to NaN
imdb['Gross'] = imdb['Gross'].str.replace(',', '', regex=False)
imdb['Gross'] = pd.to_numeric(imdb['Gross'], errors='coerce')

# Display info to verify the data type change
display(imdb['Gross'].info())

<class 'pandas.core.series.Series'>
RangeIndex: 1000 entries, 0 to 999
Series name: Gross
Non-Null Count  Dtype
--------------  -----
831 non-null    float64
dtypes: float64(1)
memory usage: 7.9 KB

None

In [64]:
# Next, redo the sorting on Gross

# Select all movies released after (>=) 2010 and with IMDB_Rating>=8.5
# Show their title, released year, Certificate, and gross.
# Sort them in descending order of "Gross"
movies = imdb[(imdb['Released_Year'] >= 2010) & (imdb['IMDB_Rating'] >= 8.5)]
movies[['Series_Title', 'Released_Year', 'Certificate', 'Gross']].sort_values(by='Gross', ascending=False)

        Series_Title  Released_Year Certificate        Gross
33             Joker           2019           A  335451311.0
8          Inception           2010          UA  292576195.0
21      Interstellar           2014          UA  188020017.0
19      Gisaengchung           2019           A   53367844.0
35  The Intouchables           2011          UA   13182281.0
34          Whiplash           2014           A   13092000.0
18          Hamilton           2020       PG-13          NaN
20   Soorarai Pottru           2020           U          NaN

In [65]:
# Add a new column "Runtime_min" by removing the substring " min" in "Runtime"
# Set its data type as int
# Hint: https://stackoverflow.com/questions/36505847/substring-of-an-entire-column-in-pandas-dataframe

imdb['Runtime_min'] = imdb['Runtime'].str.replace(' min', '', regex=False)
imdb['Runtime_min'] = imdb['Runtime_min'].astype(int)

<class 'pandas.core.series.Series'>
RangeIndex: 1000 entries, 0 to 999
Series name: Runtime_min
Non-Null Count  Dtype
--------------  -----
1000 non-null   int64
dtypes: int64(1)
memory usage: 7.9 KB

In [68]:
# Add a new column "Age_Year" by expression: Current year - Released_Year
import datetime

current_year = datetime.datetime.now().year
imdb['Age_Year'] = current_year - imdb['Released_Year']

imdb[['Series_Title', 'Released_Year', 'Age_Year']].head()

               Series_Title  Released_Year  Age_Year
0  The Shawshank Redemption           1994        32
1             The Godfather           1972        54
2           The Dark Knight           2008        18
3    The Godfather: Part II           1974        52
4              12 Angry Men           1957        69

In [69]:
# Add a new column "Decade" with values as 1980, 1990, 2000, 2010, 2020, etc.
imdb['Decade'] = (imdb['Released_Year'] // 10) * 10
display(imdb[['Series_Title', 'Released_Year', 'Decade']].head())

               Series_Title  Released_Year  Decade
0  The Shawshank Redemption           1994    1990
1             The Godfather           1972    1970
2           The Dark Knight           2008    2000
3    The Godfather: Part II           1974    1970
4              12 Angry Men           1957    1950

## Part 2: Data Summarization

In [70]:
# Total "Gross" of all top 1000 movies
total_gross = imdb['Gross'].sum()
print(f"Total Gross of all top 1000 movies: ${total_gross:,.2f}")

Total Gross of all top 1000 movies: $56,536,877,976.00

In [71]:
# Average "No_of_Votes" of all movies
average_votes = imdb['No_of_Votes'].mean()
print(f"Average number of votes for all movies: {average_votes:,.2f}")

Average number of votes for all movies: 273,692.91

In [72]:
# Count movies in each decade (e.g., ..., 1980, 1990, 2000, 2010, 2020)
# Sort decades by the number of movies in descending order
decade_counts = imdb['Decade'].value_counts().sort_index()
display(decade_counts)

Decade
1920     11
1930     24
1940     35
1950     56
1960     73
1970     76
1980     89
1990    151
2000    237
2010    242
2020      6
Name: count, dtype: int64

In [73]:
# Count movies by different directors.
# Show the top 10 directors with the most movies in this list
director_counts = imdb['Director'].value_counts()
display(director_counts.head(10))

Director
Alfred Hitchcock     14
Steven Spielberg     13
Hayao Miyazaki       11
Akira Kurosawa       10
Martin Scorsese      10
Woody Allen           9
Stanley Kubrick       9
Billy Wilder          9
Clint Eastwood        8
Christopher Nolan     8
Name: count, dtype: int64

In [74]:
# For each director, calculate the number of movies, average IMDB_Rating, and total gross.
# Ranked in descending order of total gross
# Show the top 10 directors with the most gross
director_summary = imdb.groupby('Director').agg(
    num_movies=('Series_Title', 'count'),
    average_imdb_rating=('IMDB_Rating', 'mean'),
    total_gross=('Gross', 'sum')
).sort_values(by='total_gross', ascending=False)

display(director_summary.head(10))

                   num_movies  average_imdb_rating   total_gross
Director
Steven Spielberg           13             8.030769  2.478133e+09
Anthony Russo               4             8.075000  2.205039e+09
Christopher Nolan           8             8.462500  1.937454e+09
James Cameron               5             8.080000  1.748237e+09
Peter Jackson               5             8.400000  1.597312e+09
J.J. Abrams                 3             7.833333  1.423171e+09
Brad Bird                   4             7.900000  1.099628e+09
Robert Zemeckis             5             8.120000  1.049446e+09
David Yates                 3             7.800000  9.789537e+08
Pete Docter                 4             8.125000  9.393821e+08

In [75]:
# Group movies by decade and director
# In each group (i.e., for each decade and each director),
# calculate the number of movies and average IMDB rating.
# Sort in descending order of movie count
decade_director_summary = imdb.groupby(['Decade', 'Director']).agg(
    num_movies=('Series_Title', 'count'),
    average_imdb_rating=('IMDB_Rating', 'mean')
).sort_values(by='num_movies', ascending=False)

display(decade_director_summary.head(10))

                          num_movies  average_imdb_rating
Decade Director
1950   Billy Wilder                6             8.133333
       Akira Kurosawa              5             8.260000
2010   Denis Villeneuve            5             7.980000
1950   Alfred Hitchcock            5             8.220000
1980   Steven Spielberg            5             7.980000
1940   Alfred Hitchcock            5             7.880000
2000   Clint Eastwood              5             7.940000
       Christopher Nolan           4             8.525000
1960   Sergio Leone                4             8.400000
1990   Joel Coen                   4             7.900000

In [76]:
# Find the top 3 highest rated movies of each year since 2010.
# Show their released year, ranking, title, and IMDB_Rating.
# Sort them in descending order of year and ascending order of ranking

# Filter for movies released in or after 2010
movies_since_2010 = imdb[imdb['Released_Year'] >= 2010]

# Group by 'Released_Year' and select the top 3 by 'IMDB_Rating'
top_movies_per_year = movies_since_2010.groupby('Released_Year').apply(
    lambda x: x.nlargest(3, 'IMDB_Rating')
).reset_index(drop=True)

# Select desired columns and sort
result = top_movies_per_year[['Released_Year', 'Series_Title', 'IMDB_Rating']].sort_values(
    by=['Released_Year', 'IMDB_Rating'],
    ascending=[False, False]
)

result

/tmp/ipykernel_5378/3242602395.py:9: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  top_movies_per_year = movies_since_2010.groupby('Released_Year').apply(

    Released_Year                       Series_Title  IMDB_Rating
30           2020                           Hamilton          8.6
31           2020                    Soorarai Pottru          8.6
32           2020                               Soul          8.1
27           2019                       Gisaengchung          8.6
28           2019                              Joker          8.5
29           2019                  Avengers: Endgame          8.4
24           2018                         Capharnaüm          8.4
25           2018  Spider-Man: Into the Spider-Verse          8.4
26           2018             Avengers: Infinity War          8.4
21           2017          Ayla: The Daughter of War          8.4
22           2017                       Vikram Vedha          8.4
23           2017                               Coco          8.4
18           2016                     Kimi no na wa.          8.4
19           2016                             Dangal          8.4
20           2016                               Pink          8.1
15           2015                             Talvar          8.2
16           2015                           Drishyam          8.2
17           2015                               Room          8.1
12           2014                       Interstellar          8.6
13           2014                           Whiplash          8.5
14           2014                              Mommy          8.1
9            2013                           Drishyam          8.3
10           2013                              Queen          8.2
11           2013                        Mandariinid          8.2
6            2012                   Django Unchained          8.4
7            2012              The Dark Knight Rises          8.4
8            2012                             Jagten          8.3
3            2011                   The Intouchables          8.5
4            2011            Jodaeiye Nader az Simin          8.3
5            2011                            Warrior          8.2
0            2010                          Inception          8.8
1            2010                          Incendies          8.3
2            2010                              Udaan          8.2

In [77]:
# Find all directors whose movies appeared in at least five different decades.
# Your result should include: director, decade, and the number of movies in the decade.

# Group by Director and Decade to count movies per decade for each director
director_decade_counts = imdb.groupby(['Director', 'Decade']).size().reset_index(name='num_movies')

# Count the number of unique decades each director has movies in
decade_diversity = director_decade_counts.groupby('Director')['Decade'].nunique().reset_index(name='num_decades')

# Filter for directors who have movies in at least five different decades
multi_decade_directors = decade_diversity[decade_diversity['num_decades'] >= 5]

# Filter the original director_decade_counts to include only these directors
result = director_decade_counts[director_decade_counts['Director'].isin(multi_decade_directors['Director'])]

# Sort for better readability (optional)
result = result.sort_values(by=['Director', 'Decade'])

display(result)

             Director  Decade  num_movies
247    Hayao Miyazaki    1970           1
248    Hayao Miyazaki    1980           4
249    Hayao Miyazaki    1990           2
250    Hayao Miyazaki    2000           3
251    Hayao Miyazaki    2010           1
424   Martin Scorsese    1970           1
425   Martin Scorsese    1980           3
426   Martin Scorsese    1990           2
427   Martin Scorsese    2000           1
428   Martin Scorsese    2010           3
644  Steven Spielberg    1970           2
645  Steven Spielberg    1980           5
646  Steven Spielberg    1990           3
647  Steven Spielberg    2000           2
648  Steven Spielberg    2010           1

In [81]:
# Ask two questions about this dataset and write your code to answer them.
# Question 1: What is the average IMDB rating of all movies in the dataset?
average_imdb_rating = imdb['IMDB_Rating'].mean()
print(f"Average IMDB Rating: {average_imdb_rating:.2f}")

Average IMDB Rating: 7.95

In [80]:
# Questions 2: Create a new temporary dataset containing the movie title, the decade it was released,
# its IMDB rating, and its genre. Since the movies have multiple genres listed in a single string,
# break the string apart so that each individual genre gets its own row in the new dataset
df_genre_temp = imdb[['Series_Title', 'Decade', 'IMDB_Rating', 'Genre']].copy()
df_genre_temp['Genre'] = df_genre_temp['Genre'].str.split(', ')
expanded_genres = df_genre_temp.explode('Genre')

expanded_genres

                 Series_Title  Decade  IMDB_Rating     Genre
0    The Shawshank Redemption    1990          9.3     Drama
1               The Godfather    1970          9.2     Crime
1               The Godfather    1970          9.2     Drama
2             The Dark Knight    2000          9.0    Action
2             The Dark Knight    2000          9.0     Crime
..                        ...     ...          ...       ...
998                  Lifeboat    1940          7.6     Drama
998                  Lifeboat    1940          7.6       War
999              The 39 Steps    1930          7.6     Crime
999              The 39 Steps    1930          7.6   Mystery
999              The 39 Steps    1930          7.6  Thriller

[2541 rows x 4 columns]